server:
  port: 8181
spring:
  config:
    activate:
      on-profile: stg
  datasource:
    url: jdbc:mysql://localhost:3306/PBL6
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true