server:
  port: 8181
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/PBL6
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    locations: classpath:/db/migration
    baseline-on-migrate: true
    baseline-version: 0
  jackson:
    date-format: yyyy-MM-dd
    time-zone: UTC
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false